namespace VehicleRentalSystem.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ModifyEmailAddressTable_MakeEmailAddressIdAutoGenerated : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.EmailAddresses");
            AlterColumn("dbo.EmailAddresses", "EmailAddressId", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.EmailAddresses", new[] { "BusinessEntityId", "EmailAddressId" });
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.EmailAddresses");
            AlterColumn("dbo.EmailAddresses", "EmailAddressId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.EmailAddresses", new[] { "BusinessEntityId", "EmailAddressId" });
        }
    }
}
